version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./poetry.lock:/app/poetry.lock:ro
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - PYTHONPATH=/app
